search_algorithm: vns # Options: vns, gns
dimension: 2

vns:
  x_range: [-500, 500]
  neighborhoods: 5
  local_search_maximum_iterations: 500
  vns_maximum_neighborhood_iterations: 20
  convergence_threshold: 0.01
